- name: Play Varaibles
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print Play Variable
      ansible.builtin.debug:
        msg: URL ={{URL}}



- name: Play Varaibles from file
  hosts: localhost
  ## vars_files works only on play levels
  vars_files:
    - var.yml
  tasks:
    - name: Print Play Variables from file
      ansible.builtin.debug:
        msg: URL ={{URL}}

- name: Task Level Variable
  hosts: localhost
  tasks:
    - name: Print Task level variable from this task
      #These vars are only for this task, next task on the same play can't access this variable.
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL ={{URL}}

- name: Variables from Inventory file
  # inventory file host can be a group or 'all' for everything
  hosts: all
  tasks: # variable values must be filled in inventory file (/tmp/inv) and pass FILENAME in ansible command.
    - name: Print play variables from inventory file
      ansible.builtin.debug:
        msg: URL ={{URL}}