- name: Play Varaibles
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print Play Variable
      ansible.builtin.debug:
        msg: URL ={{URL}}



- name: Play Varaibles from file
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: Print Play Variables from file
      ansible.builtin.debug:
        msg: URL ={{URL}}