- name: filters
  hosts: localhost
  vars:
    URL: https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz
  tasks:
    - name: string filters 
      debug:
        msg: "{{ URL | split('/') | last | regex_replace('.tar.gz')}}"
